---
# System domain - Essential host layer components
- name: Upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: full

- name: Install system packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest # noqa package-latest
  loop: "{{ setup_system_apt }}"

- name: Setup Flatpak
  ansible.builtin.import_role:
    name: alvistack.flatpak

- name: Install Nix package manager
  ansible.builtin.import_role:
    name: danielrolls.nix

- name: >-
    Remove dependencies that are no longer required and purge their
    configuration files
  ansible.builtin.apt:
    autoremove: true
    purge: true

- name: Ensure a locale exists
  community.general.locale_gen:
    name: "{{ setup_system_locale }}"
    state: present

- name: Set timezone
  community.general.timezone:
    name: "{{ setup_system_timezone }}"

- name: Set shell to prefer dark mode
  community.general.dconf:
    key: "/org/gnome/shell/ubuntu/color-scheme"
    value: "'prefer-dark'"
    state: present
  when:
    - not docker_test_env

- name: Set appearance to prefer dark mode
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
    state: present
  when:
    - not docker_test_env

- name: Pin system favorites to GNOME launcher
  ansible.builtin.include_role:
    name: gnome_favorites
  vars:
    gnome_favorites_list: "{{ setup_system_favorites }}"
