---
- name: Install oh-my-zsh
  ansible.builtin.include_role:
    name: gantsign.oh-my-zsh
  vars:
    oh_my_zsh_plugins: "{{ zsh_plugins }}"
    oh_my_zsh_update_mode: auto
    users:
      - username: "{{ ansible_user }}"

- name: Install Starship
  ansible.builtin.include_role:
    name: bartdorlandt.starship

- name: Configure zsh plugins
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user }}/.zshrc"
    content: |
      zstyle ':omz:update' mode auto

      # NVM Autoload
      zstyle ':omz:plugins:nvm' autoload yes

      # Starship
      eval "$(starship init zsh)"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Define aliases
  ansible.builtin.include_role:
    name: redbeard28.bashaliases
  vars:
    shell_aliases:
      - { alias: "cat", command: "batcat -pp" }
      # Enforce security for git aliases
      - { alias: "ggl", command: "ggfl" }
      - { alias: "gcam", command: "gcasm" }
      - { alias: "gcan!", command: "gcans!" }
