---
- name: Check whether zsh is available
  ansible.builtin.shell: |
    command -v zsh >/dev/null 2>&1 && echo ok || echo missing
  register: zsh_check
  ignore_errors: true
  changed_when: false

- name: Stat user's .zshrc
  ansible.builtin.stat:
    path: "/home/{{ ansible_user }}/.zshrc"
  register: zshrc_stat
  become: false

- name: Install oh-my-zsh
  ansible.builtin.shell: |
    set -o pipefail
    export RUNZSH=no
    export CHSH=no
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "/home/{{ ansible_user }}/.zshrc"
    executable: /bin/bash
  register: oh_my_zsh_install
  become: true
  become_user: "{{ ansible_user }}"
  when: zsh_check.rc == 0

- name: Ensure .zshrc ownership
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.zshrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  when: zshrc_stat.stat.exists
  become: true

- name: Install zsh plugins
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    regexp: "^plugins="
    line: "plugins=({{ setup_shell_zsh_plugins | join(' ') }})"
  when: setup_shell_zsh_plugins | length > 0 and zshrc_stat.stat.exists

- name: Setup zsh aliases
  ansible.builtin.lineinfile:
    dest: "/home/{{ ansible_user }}/.zsh_aliases"
    create: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "^alias {{ item.alias }}="
  with_items: "{{setup_shell_zsh_aliases}}"
  when: setup_shell_zsh_aliases | length > 0

- name: Download Starship install script
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship-install.sh
    mode: "0755"
    force: true

- name: Install Starship
  ansible.builtin.shell: |
    set -o pipefail
    /bin/sh /tmp/starship-install.sh --force
  args:
    creates: "/usr/local/bin/starship"
    executable: /bin/bash
  register: starship_install
  become: true
  become_user: "{{ ansible_user }}"

- name: Remove installer script
  ansible.builtin.file:
    path: /tmp/starship-install.sh
    state: absent

- name: Verify Starship installation
  ansible.builtin.command: /usr/local/bin/starship --version
  changed_when: false

- name: Configure starship in zsh
  ansible.builtin.blockinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    insertafter: EOF
    block: |
      eval "$(starship init zsh)"
  when: zshrc_stat.stat.exists

- name: Configure zsh NVM plugin
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    search_string: "zstyle ':omz:plugins:nvm'"
    insertafter: "zstyle '"
    line: "zstyle ':omz:plugins:nvm' autoload yes"
  when: zshrc_stat.stat.exists
