version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "04:00"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    open-pull-requests-limit: 20
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      docker-dependencies:
        patterns:
          - "*"
