---
- name: Upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: full

- name: Install apt repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ setup_apt_repositories }}"
  retries: 3
  delay: 10

- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest # noqa package-latest
  loop: "{{ setup_apt_packages }}"

- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: yes
    purge: true
