services:
  ubuntu:
    image: ${UBUNTU_IMAGE}
    environment:
      VNC_PW: password
      REPOSITORY_URL:
      REPOSITORY_BRANCH:
      BITWARDEN_EMAIL:
      BITWARDEN_PASSWORD:
    shm_size: 1024m
    cap_add:
      - SYS_PTRACE
