services:
  ansible:
    build:
      context: .
      dockerfile: docker/ansible/Dockerfile
      target: ci
    volumes:
      - ./ansible:/ansible
    env_file:
      - .env
    stdin_open: true
    tty: true
    init: true

  ubuntu:
    build:
      context: docker/ubuntu
    environment:
      REPOSITORY_URL: http://git/ubuntu-config.git
      REPOSITORY_BRANCH: main
      VNC_PW: password
    shm_size: 1024m
    cap_add:
      - SYS_PTRACE
    ports:
      - 6901:6901
    env_file:
      - .env

  git:
    build:
      context: .
      dockerfile: docker/git/Dockerfile
    volumes:
      - ./install.sh:/srv/source/ubuntu-config/install.sh:ro
      - ./ansible:/srv/source/ubuntu-config/ansible:ro
    ports:
      - 8088:80
