---
services:
  ansible:
    build:
      context: .
      dockerfile: docker/ansible/Dockerfile
      target: ci
    volumes:
      - ./ansible:/ansible
      - ./vm:/workspace/vm
    env_file:
      - .env
    stdin_open: true
    tty: true
    init: true

  git:
    build:
      context: .
      dockerfile: docker/git/Dockerfile
    volumes:
      - ./install.sh:/srv/source/ubuntu-config/install.sh:ro
      - ./ansible:/srv/source/ubuntu-config/ansible:ro
    ports:
      - 8088:80

  test:
    build:
      context: ./docker/test
      dockerfile: Dockerfile
    volumes:
      - ./tests:/workspace/tests:ro
      - ./tests/.pytest_cache:/workspace/tests/.pytest_cache:rw
      - ./vm:/workspace/vm:ro
    env_file:
      - .env
    stdin_open: true
    tty: true
