---
services:
  ubuntu:
    image: ${UBUNTU_IMAGE}
    environment:
      VNC_PW: password
      REPOSITORY_URL:
      REPOSITORY_BRANCH:
      BITWARDEN_EMAIL:
      BITWARDEN_PASSWORD:
      BITWARDEN_CLIENT_ID:
      BITWARDEN_CLIENT_SECRET:
    shm_size: 1024m
    cap_add:
      - SYS_PTRACE

  test:
    image: ${TEST_IMAGE}
    volumes:
      - .:/workspace
    working_dir: /workspace
    depends_on:
      - ubuntu
