version: "3"
services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile.ansible
      target: ci
    volumes:
      - ./ansible:/ansible
      - .ssh/ansible:/root/.ssh/ansible:ro
    environment:
      ANSIBLE_USER:
      ANSIBLE_PASSWORD:

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    shm_size: 1024m
    cap_add:
      - SYS_PTRACE
    volumes:
      - .ssh/ansible.pub:/home/test/.ssh/ansible.pub:ro
