version: "3"
services:
  ansible:
    image: ${ANSIBLE_IMAGE}

  ubuntu:
    image: ${UBUNTU_IMAGE}
    shm_size: 1024m
    cap_add:
      - SYS_PTRACE
    environment:
      REPOSITORY_URL: http://git/ubuntu-config.git
      REPOSITORY_BRANCH: main

  git:
    image: ${GIT_IMAGE}
