version: "3"
services:
  ansible:
    build:
      context: .
      dockerfile: docker/ansible/Dockerfile
      target: ci
    volumes:
      - ./ansible:/ansible
      - ./multipass:/multipass
    env_file:
      - .env

  ubuntu:
    build:
      context: docker/ubuntu
    shm_size: 1024m
    cap_add:
      - SYS_PTRACE
    environment:
      REPOSITORY_URL: http://git/ubuntu-config.git
      REPOSITORY_BRANCH: main
      VNC_PW: password
      BITWARDEN_EMAIL:
      BITWARDEN_PASSWORD:
    ports:
      - 6901:6901

  git:
    build:
      context: .
      dockerfile: docker/git/Dockerfile
    volumes:
      - ./install.sh:/var/lib/git/ubuntu-config/install.sh:ro
      - ./ansible:/var/lib/git/ubuntu-config/ansible:ro
