#cloud-config
hostname: ubuntu-config-test
users:
  - name: "{{USERNAME}}" # dynamically injected by GitHub Actions
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: "{{HASHED_PASSWORD}}" # dynamically injected by GitHub Actions
    ssh_authorized_keys:
      - "{{SSH_PUBLIC_KEY}}" # dynamically injected by GitHub Actions

ssh_pwauth: true

chpasswd:
  expire: false

packages:
  - ubuntu-desktop
  - openssh-server

bootcmd:
  - mkdir -p /home/{{USERNAME}}/.ssh
  - echo "{{SSH_PUBLIC_KEY}}" > /home/{{USERNAME}}/.ssh/authorized_keys
  - chown -R {{USERNAME}}:{{USERNAME}} /home/{{USERNAME}}/.ssh
  - chmod 700 /home/{{USERNAME}}/.ssh
  - chmod 600 /home/{{USERNAME}}/.ssh/authorized_keys

runcmd:
  - systemctl enable ssh
  - systemctl start ssh
  - cloud-init status --wait
  - echo "✅ SSH should now be active for user {{USERNAME}}"
  - touch /e2e.ready
