#cloud-config
hostname: ubuntu-config-test
users:
  - name: "{{USERNAME}}" # dynamically injected by GitHub Actions
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: "{{HASHED_PASSWORD}}" # dynamically injected by GitHub Actions
    ssh_authorized_keys:
      - "{{SSH_PUBLIC_KEY}}" # dynamically injected by GitHub Actions

ssh_pwauth: true
disable_root: false

chpasswd:
  expire: false

packages:
  - openssh-server

runcmd:
  - systemctl enable ssh
  - systemctl start ssh
  - echo "✅ SSH should now be active"
