---
# Development domain - Development tools, and project setup
- name: Install development applications via Flatpak
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ setup_development_flatpak | default([]) }}"

- name: Setup development project directories
  ansible.builtin.file:
    path: "{{ setup_development_projects_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  when: setup_development_projects_directory is defined

- name: Configure Max files watches
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present

- name: Pin development favorites to GNOME launcher
  ansible.builtin.include_role:
    name: gnome_favorites
  vars:
    gnome_favorites_list: "{{ setup_development_favorites }}"
