---
# Browser domain - Web browsers and related tools
- name: Install browser applications via Flatpak
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ setup_browser_flatpak }}"
  when: not docker_test_env

- name: Setup default web browser
  ansible.builtin.include_role:
    name: gantsign.default-web-browser
  vars:
    default_web_browser: "{{ setup_browser_favorites[0] }}"

- name: Pin browser favorites to GNOME launcher
  ansible.builtin.include_role:
    name: gnome_favorites
  vars:
    gnome_favorites_list: "{{ setup_browser_favorites }}"
