---
- name: Install php
  ansible.builtin.apt:
    name: "php"
    state: latest

- name: Install composer
  ansible.builtin.include_role:
    name: geerlingguy.composer
  vars:
    composer_keep_updated: true
    composer_global_packages: "{{ composer_packages }}"
    composer_home_owner: "{{ ansible_user }}"
    composer_home_group: "{{ ansible_user }}"

- name: Create global composer config
  ansible.builtin.copy:
    content: "{}"
    dest: "/home/{{ ansible_user }}/.composer/composer.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Retrieve list of globally installed Composer packages
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.command: composer global show --direct --format=json
  register: composer_packages_output
  changed_when: false

- name: Parse list of installed Composer packages
  ansible.builtin.set_fact:
    installed_composer_packages: "{{ composer_packages_output.stdout_lines[0] | from_json | community.general.json_query('installed[*].name') | default([], true) }}"

- name: Remove useless installed Composer packages.
  become: true
  become_user: "{{ ansible_user }}"
  community.general.composer:
    global_command: true
    command: remove
    arguments: "{{ item }}"
  loop: "{{ installed_composer_packages }}"
  when: item not in composer_packages
