---
- name: Create profile file
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.profile
    state: touch
    modification_time: preserve
    access_time: preserve
    mode: 0644
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Install nvm
  ansible.builtin.include_role:
    name: stephdewit.nvm
    apply:
      become: true
      become_user: "{{ ansible_user }}"
      environment:
        NVM_DIR: /home/{{ ansible_user }}/.nvm
  vars:
    nvm_version: "latest"
    nvm_node_version: "node"

- name: Install yarn
  ansible.builtin.include_role:
    name: Oefenweb.yarn

- name: Retrieve list of globally installed Yarn packages
  become: true
  ansible.builtin.command: yarn global list --depth=0
  register: setup_dev_yarn_packages_output
  changed_when: false

- name: Parse list of installed Yarn packages
  ansible.builtin.set_fact:
    installed_packages: "{{ setup_dev_yarn_packages_output.stdout_lines | select('match', '^info .*@') | map('regex_replace', '^info\\s+([^@]+)@.*$', '\\1') | list }}"

- name: Remove useless installed Yarn packages.
  become: true
  community.general.yarn:
    name: "{{ item }}"
    global: true
    state: absent
  loop: "{{ installed_packages }}"
  when: item not in setup_dev_yarn_packages

- name: Install Yarn global packages
  become: true
  community.general.yarn:
    name: "{{ item }}"
    state: "latest"
    global: true
  loop: "{{ setup_dev_yarn_packages }}"
