# GPG keys setup
# Generated keys with: gpg --expert --full-generate-key
# Exported with:
# gpg --export --armor your@id.here > your@id.here.pub.asc
# gpg --export-secret-keys --armor your@id.here > your@id.here.priv.asc
# gpg --export-secret-subkeys --armor your@id.here > your@id.here.sub_priv.asc
# gpg --export-ownertrust > ownertrust.txt
---
# FIXME: should use community.general.bitwarden
# "{{ lookup('community.general.bitwarden', collection_id=setup_keys_bitwarden_gpg_keys_collection_id, bw_session=bw_session) }}"
- name: Retrieve GPG keys from Bitwarden
  delegate_to: localhost
  ansible.builtin.command: bw list items --collectionid "{{ setup_keys_bitwarden_gpg_keys_collection_id }}" --session "{{ bw_session | default('') }}" --response
  register: bw_items
  changed_when: false
  no_log: true

- ansible.builtin.set_fact:
    gpg_keys: |
      {{ 
        bw_items.stdout 
        | from_json 
        | community.general.json_query(gpg_keys_query)
      }}
  vars:
    gpg_keys_query: |
      data.data[].{
        name: name,
        public_key: fields[?name=='public_key'].value | [0]
        private_key: fields[?name=='private_key'].value | [0]
        sub_private_key: fields[?name=='sub_private_key'].value | [0]
        ownertrust: fields[?name=='ownertrust'].value | [0]
      }
  no_log: true

- name: Setup GPG keys
  ansible.builtin.include_tasks: setup-gpg-key.yml
  vars:
    key_name: "{{ item.name }}"
    public_key: "{{ item.public_key }}"
    private_key: "{{ item.private_key }}"
    sub_private_key: "{{ item.sub_private_key }}"
    ownertrust: "{{ item.ownertrust }}"
  loop: "{{ gpg_keys }}"
  loop_control:
    label: "{{ item.name }}"
