---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    mode: "0700"

- name: Ensure setup_keys_bitwarden_ssh_keys_collection_id is set
  ansible.builtin.fail:
    msg: "setup_keys_bitwarden_ssh_keys_collection_id is required"
  when: not setup_keys_bitwarden_ssh_keys_collection_id

# FIXME: should use community.general.bitwarden
# "{{ lookup('community.general.bitwarden', collection_id=setup_keys_bitwarden_ssh_keys_collection_id, bw_session=bw_session) }}"
- name: Retrieve ssh keys from Bitwarden
  delegate_to: localhost
  ansible.builtin.command: bw list items --collectionid "{{ setup_keys_bitwarden_ssh_keys_collection_id }}" --session "{{ bw_session }}" --response
  register: bw_items
  changed_when: false

- ansible.builtin.set_fact:
    ssh_keys: |
      {{ 
        bw_items.stdout 
        | from_json 
        | community.general.json_query(ssh_keys_query)
      }}
  vars:
    ssh_keys_query: |
      data.data[].{
        name: name,
        public_key: fields[?name=='public_key'].value | [0],
        private_key: fields[?name=='private_key'].value | [0]
      }

- name: Setup SSH keys from Bitwarden
  ansible.builtin.include_tasks: setup-ssh-key.yml
  vars:
    key_name: "{{ item.name }}"
    private_key: "{{ item.private_key }}"
    public_key: "{{ item.public_key }}"
  loop: "{{ ssh_keys }}"
  loop_control:
    label: "{{ item.name }}"
