---
# FIXME: should use community.general.bitwarden
# "{{ lookup('community.general.bitwarden', collection_id=setup_keys_bitwarden_gpg_keys_collection_id, bw_session=bw_session) }}"
- name: Retrieve GPG keys from Bitwarden
  delegate_to: localhost
  ansible.builtin.command: bw list items --collectionid "{{ setup_keys_bitwarden_gpg_keys_collection_id }}" --session "{{ bw_session }}" --response
  register: bw_items
  changed_when: false

- ansible.builtin.set_fact:
    gpg_keys: |
      {{ 
        bw_items.stdout 
        | from_json 
        | community.general.json_query(gpg_keys_query)
      }}
  vars:
    # FIXME: GPG Private key exceed the field size limit so it is stored in notes
    # private_key: fields[?name=='private_key'].value | [0]
    gpg_keys_query: |
      data.data[].{
        name: name,
        private_key: notes,
        public_key: fields[?name=='public_key'].value | [0]
      }

- name: Setup GPG keys
  ansible.builtin.include_tasks: setup-gpg-key.yml
  vars:
    key_name: "{{ item.name }}"
    private_key: "{{ item.private_key }}"
    public_key: "{{ item.public_key }}"
  loop: "{{ gpg_keys }}"
  loop_control:
    label: "{{ item.name }}"
