---
- name: Setup dev folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - "{{ setup_dev_projects_directory }}"
  tags: dev

- name: Setup Git
  ansible.builtin.import_tasks: setup-git.yml
  tags: git

- name: Setup NodeJS
  ansible.builtin.import_tasks: setup-nodejs.yml
  tags: nodejs

- name: Setup PHP
  ansible.builtin.import_tasks: setup-php.yml
  tags: php
