---
- name: Setup snap packages
  when: not ansible_module_running_in_container
  community.general.snap:
    name: "{{ item }}"
    classic: yes
  loop: "{{ setup_snap_packages }}"

- name: Refresh snap packages
  when: not ansible_module_running_in_container
  ansible.builtin.command: snap refresh
