---
- name: Get facts on current container
  community.docker.current_container_facts:

- name: Setup snap packages
  when: not ansible_module_running_in_container
  community.general.snap:
    name: "{{ item }}"
    classic: yes
  loop: "{{ snap_packages }}"

- name: Refresh snap packages
  when: not ansible_module_running_in_container
  ansible.builtin.command: snap refresh
