---
# Utility domain - System utilities and maintenance tools
- name: Add utility APT repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: present
  loop: "{{ setup_utility_repositories }}"

- name: Install utility packages via APT
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest  # noqa package-latest
  loop: "{{ setup_utility_apt }}"

- name: Install utility applications via Flatpak
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ setup_utility_flatpak }}"
  when: flatpak_available | default(true)
  ignore_errors: "{{ not (flatpak_available | default(true)) }}"

- name: Pin utility favorites to GNOME launcher
  ansible.builtin.include_role:
    name: gnome_favorites
  vars:
    gnome_favorites_list: "{{ setup_utility_favorites }}"
