---
# Utility domain - System utilities and maintenance tools

# uCareSystem installation via direct .deb download
- name: Get latest uCareSystem release information
  ansible.builtin.uri:
    url: https://api.github.com/repos/Utappia/uCareSystem/releases/latest
    method: GET
    return_content: true
  register: ucaresystem_release
  when: "'ucaresystem-core' in setup_utility_apt"

- name: Extract uCareSystem .deb download URL
  ansible.builtin.set_fact:
    ucaresystem_deb_url: >-
      {{
        (ucaresystem_release.json.assets |
         selectattr('name', 'match', '.*\.deb$') |
         first).browser_download_url
      }}
  when: "'ucaresystem-core' in setup_utility_apt"

- name: Download and install uCareSystem .deb package
  ansible.builtin.apt:
    deb: "{{ ucaresystem_deb_url }}"
    state: present
  when: "'ucaresystem-core' in setup_utility_apt"

# Install other utility packages (excluding ucaresystem-core handled above)
- name: Install utility packages via APT
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest # noqa package-latest
  loop: "{{ setup_utility_apt | difference(['ucaresystem-core']) }}"
  when: >-
    setup_utility_apt | difference(['ucaresystem-core']) | length > 0

- name: Install utility applications via Flatpak
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ setup_utility_flatpak }}"
  when: flatpak_available | default(true)

- name: Pin utility favorites to GNOME launcher
  ansible.builtin.include_role:
    name: gnome_favorites
  vars:
    gnome_favorites_list: "{{ setup_utility_favorites }}"
