---
- name: Upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: full

- name: Install apt repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ apt_repositories }}"

- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ apt_packages }}"

- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: yes
    purge: true
