---
- name: Install requirements
  hosts: personal_computer
  become: true
  vars:
    ansible_config_dir: "/home/ansible/config"

  tasks:
    - name: Install ansible galaxy requirements
      community.general.ansible_galaxy_install:
        type: both
        requirements_file: ./requirements.yml
      tags: requirements
