personal_computer:
  hosts:
    localhost:
      ansible_connection: local
      ansible_host: localhost
      ansible_user: root

    ubuntu-config-test:
      ansible_user: ubuntu
      ansible_host: "{{ ANSIBLE_HOST | default('127.0.0.1') }}"
      ansible_port: "{{ ansible_port | default(22) }}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ControlMaster=no -o ControlPath=none"
      ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file | default('/workspace/vm/id_rsa') }}"
