---
# Reusable role for pinning applications to GNOME launcher favorites
- name: Get current GNOME launcher favorites
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    state: read
  register: gnome_favorites_current_favorites
  when: >-
    not docker_test_env and
    gnome_favorites_list is defined and
    gnome_favorites_list | length > 0
  become: false

- name: Parse current favorites when value exists and is valid
  ansible.builtin.set_fact:
    gnome_favorites_current_list: >-
      {{
        gnome_favorites_current_favorites.value
        | regex_replace("'", '"')
        | from_json
      }}
  when: >-
    not docker_test_env and
    gnome_favorites_list is defined and
    gnome_favorites_list | length > 0 and
    gnome_favorites_current_favorites.value is defined and
    gnome_favorites_current_favorites.value is not none and
    gnome_favorites_current_favorites.value | string | length > 0 and
    gnome_favorites_current_favorites.value != ""
  failed_when: false

- name: Set empty list when no current favorites
  ansible.builtin.set_fact:
    gnome_favorites_current_list: []
  when: >-
    not docker_test_env and
    gnome_favorites_list is defined and
    gnome_favorites_list | length > 0 and
    (gnome_favorites_current_list is not defined)

- name: Pin applications to GNOME launcher
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: >-
      {{
        (
          (gnome_favorites_current_list | default([])) +
          (gnome_favorites_list | default([]))
        )
        | unique
        | to_json
      }}
    state: present
  when: >-
    not docker_test_env and
    gnome_favorites_list is defined and
    gnome_favorites_list | length > 0
  become: false
