---
# Reusable role for pinning applications to GNOME launcher favorites

# Check if GUI session is available for dconf operations
- name: Check if GUI session is available for GNOME favorites
  ansible.builtin.shell: |
    # Check for desktop session indicators
    if [ -n "${XDG_CURRENT_DESKTOP:-}" ] || [ -n "${DESKTOP_SESSION:-}" ] || [ -n "${DISPLAY:-}" ]; then
      exit 0
    fi
    # Check if dbus session is available
    if command -v dbus-launch >/dev/null 2>&1 && pgrep -x dbus-daemon >/dev/null 2>&1; then
      exit 0
    fi
    # Check if we can connect to dconf without error
    if dconf read /org/gnome/shell/favorite-apps >/dev/null 2>&1; then
      exit 0
    fi
    exit 1
  register: gnome_favorites_gui_available
  failed_when: false
  changed_when: false
  when: >-
    gnome_favorites_list is defined and
    gnome_favorites_list | length > 0

- name: Get current GNOME launcher favorites
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    state: read
  register: gnome_favorites_current_favorites
  when: >-
    gnome_favorites_list is defined and
    gnome_favorites_list | length > 0 and
    gnome_favorites_gui_available.rc == 0
  become: false

- name: Parse current favorites when value exists and is valid
  ansible.builtin.set_fact:
    gnome_favorites_current_list: >-
      {{
        gnome_favorites_current_favorites.value
        | regex_replace("'", '"')
        | from_json
      }}
  when: >-
    gnome_favorites_list is defined and
    gnome_favorites_list | length > 0 and
    gnome_favorites_gui_available.rc == 0 and
    gnome_favorites_current_favorites.value is defined and
    gnome_favorites_current_favorites.value is not none and
    gnome_favorites_current_favorites.value | string | length > 0 and
    gnome_favorites_current_favorites.value != ""
  failed_when: false

- name: Set empty list when no current favorites
  ansible.builtin.set_fact:
    gnome_favorites_current_list: []
  when: >-
    gnome_favorites_list is defined and
    gnome_favorites_list | length > 0 and
    gnome_favorites_gui_available.rc == 0 and
    (gnome_favorites_current_list is not defined)

- name: Pin applications to GNOME launcher
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: >-
      {{
        (
          (gnome_favorites_current_list | default([])) +
          (gnome_favorites_list | default([]))
        )
        | unique
        | to_json
      }}
    state: present
  when: >-
    gnome_favorites_list is defined and
    gnome_favorites_list | length > 0 and
    gnome_favorites_gui_available.rc == 0
  become: false

- name: Warn about GNOME favorites configuration skip
  ansible.builtin.debug:
    msg: "⚠️  Skipping GNOME favorites configuration - no GUI session detected. Favorites will be set when desktop environment is available."
  when: >-
    gnome_favorites_list is defined and
    gnome_favorites_list | length > 0 and
    gnome_favorites_gui_available.rc != 0
