---
# Setup Home Manager for user-layer configuration management
- name: Set user home directory
  ansible.builtin.set_fact:
    user_home: "/home/{{ ansible_user }}"

- name: Ensure home configuration directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config/home-manager"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  become: false

- name: Generate Home Manager configuration from template
  ansible.builtin.template:
    src: home.nix.j2
    dest: "{{ user_home }}/.config/home-manager/home.nix"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  become: false

- name: Generate flake.nix configuration from template
  ansible.builtin.template:
    src: flake.nix.j2
    dest: "{{ user_home }}/.config/home-manager/flake.nix"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  become: false

- name: Check if Home Manager is installed
  ansible.builtin.command: which home-manager
  register: home_manager_check
  failed_when: false
  changed_when: false
  become: false

- name: Install Home Manager via Nix
  ansible.builtin.shell: |
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    nix profile install nixpkgs#home-manager
  when: home_manager_check.rc != 0
  become: false
  environment:
    USER: "{{ ansible_user }}"

- name: Initialize Home Manager configuration
  ansible.builtin.shell: |
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    cd {{ user_home }}/.config/home-manager
    home-manager switch --flake .#{{ ansible_user }}
  become: false
  environment:
    USER: "{{ ansible_user }}"
    HOME: "{{ user_home }}"
  register: home_manager_init
  changed_when: "'No change' not in home_manager_init.stdout"

- name: Add Nix profile to shell profile
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.profile"
    line: ". /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh"
    create: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  become: false

- name: Ensure user can access nix commands
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.bashrc"
    line: ". /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh"
    create: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  become: false
