export ZSH="/home/emilien/.oh-my-zsh"

# Initialize starship
eval "$(starship init zsh)"

# Plugins to install
plugins=( thefuck git yarn nvm command-not-found docker docker-compose composer aws) 

source $ZSH/oh-my-zsh.sh

# Configure plugins
zstyle ':omz:update' mode auto
zstyle ':omz:plugins:nvm' autoload yes

# Aliases

if [ "$(command -v batcat)" ]; then
  unalias -m 'cat'
  alias cat='batcat -pp'
fi

# Path

export PATH="$(yarn global bin):$(realpath ~/.local/bin):$PATH"