---
- name: Get facts on current container
  community.docker.current_container_facts:

- name: Ensure a locale exists
  community.general.locale_gen:
    name: "{{ setup_configuration_locale }}"
    state: present

- name: Set timezone
  community.general.timezone:
    name: "{{ setup_configuration_timezone }}"

- ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present

- name: Setup default web browser
  ansible.builtin.include_role:
    name: gantsign.default-web-browser
  vars:
    default_web_browser: "{{ setup_configuration_web_browser }}"

# FIXME: does not work with latest version of Jinja2: https://github.com/gantsign/ansible-role-pin-to-launcher/pull/104
# - name: Setup favorite applications
#   ansible.builtin.include_role:
#     name: gantsign.pin-to-launcher
#   vars:
#     pin_to_launcher_favorites: "{{ setup_configuration_favorites | map('regex_replace', '^(.*)$', '{\"application\": \"\\1\"}') | map('from_json') | list }}"

- name: Set shell to prefer dark mode
  community.general.dconf:
    key: "/org/gnome/shell/ubuntu/color-scheme"
    value: "'prefer-dark'"
    state: present

- name: Set appearance to prefer dark mode
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
    state: present

- name: Enable CopyQ autostart
  ansible.builtin.copy:
    src: autostart/copy-q.desktop
    dest: "/home/{{ ansible_user }}/.config/autostart/"
    mode: 0644
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Get CopyQ status
  ansible.builtin.shell: |
    copyq --check
  register: copyq_status
  ignore_errors: true

- name: Ensure CopyQ server is started
  ansible.builtin.shell: copyq
  register: copyq_start
  when: not ansible_module_running_in_container and copyq_status.rc != 0
  failed_when: copyq_start.rc != 0

- name: Configure CopyQ global shortcuts
  when: not ansible_module_running_in_container
  ansible.builtin.shell: |
    copyq eval "var cmds = commands();var cmd = cmds.find(command => command.internalId === 'copyq_global_toggle'); if(cmd){cmd.globalShortcuts = ['ctrl+shift+v'];}setCommands(cmds)"
