name: Shared - Tests - Docker

on:
  workflow_call:

permissions: {}

jobs:
  build-images:
    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@f9e149b6cdfa8443994994f10085691a57b8cf0e # 0.27.1
    permissions:
      contents: read
      packages: write
      issues: read
      pull-requests: read
      # FIXME: This is a workaround for having workflow actions. See https://github.com/orgs/community/discussions/38659
      id-token: write
    with:
      oci-registry: ${{ vars.OCI_REGISTRY }}
      images: |
        [
          {
            "name": "ubuntu-ci",
            "context": "./docker/ubuntu",
            "dockerfile": "Dockerfile",
            "platforms": ["linux/amd64"]
          }
        ]
    secrets:
      oci-registry-password: ${{ secrets.GITHUB_TOKEN }}

  tests-docker:
    name: Tests - Docker
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    needs: build-images
    env:
      BITWARDEN_EMAIL: ${{ secrets.BITWARDEN_EMAIL }}
      BITWARDEN_PASSWORD: ${{ secrets.BITWARDEN_PASSWORD }}
      INSTALL_SCRIPT: https://raw.githubusercontent.com/neilime/ubuntu-config/${{ github.head_ref || github.ref_name }}/install.sh
      REPOSITORY_URL: ${{ github.event.repository.clone_url }}
      REPOSITORY_BRANCH: ${{ github.head_ref || github.ref_name }}
      UBUNTU_IMAGE: ${{ fromJSON(needs.build-images.outputs.built-images).ubuntu-ci.images[0] }}
      DOCKER_COMPOSE_EXEC: docker compose -f compose.ci.yml exec --user kasm-user -T ubuntu sh -c
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: hoverkraft-tech/compose-action@40041ff1b97dbf152cd2361138c2b03fa29139df # v2.3.0
        with:
          compose-file: compose.ci.yml

      - name: Run install script
        run: $DOCKER_COMPOSE_EXEC "wget -qO- '""$INSTALL_SCRIPT""' | sh"

      - name: Validate Ansible changes in host - APT packages
        run: |
          if $DOCKER_COMPOSE_EXEC 'dpkg -l | grep -q "ucaresystem-core"'; then
            echo 'APT packages installed: pass' && exit 0
          else
            echo '::error ::APT packages installed: fail' && exit 1
          fi

      - name: Validate Ansible changes in host - SSH keys
        run: |
          if $DOCKER_COMPOSE_EXEC 'test -f ~/.ssh/id_rsa_escemi'; then
            echo 'SSH keys installed: pass' && exit 0
          else
            echo '::error ::SSH keys installed: fail' && exit 1
          fi

      - name: Validate Ansible changes in host - GPG keys
        run: |
          if $DOCKER_COMPOSE_EXEC 'gpg --list-keys | grep -q "/home/ubuntu/.gnupg/pubring.kbx"' ; then
            echo 'GPG keys installed: pass' && exit 0
          else
            echo '::error ::GPG keys installed: fail' && exit 1
          fi

      - name: Validate Ansible changes in host - docker
        run: |
          if $DOCKER_COMPOSE_EXEC 'docker --version | grep -q "Docker"'; then
            echo 'Docker installed: pass' && exit 0
          else
            echo '::error ::Docker installed: fail' && exit 1
          fi

          if $DOCKER_COMPOSE_EXEC 'docker-compose --version | grep -q "Docker Compose"'; then
            echo 'Docker compose installed: pass' && exit 0
          else
            echo '::error ::Docker compose installed: fail' && exit 1
          fi

      - name: Validate Ansible changes in host - zsh
        run: |
          if $DOCKER_COMPOSE_EXEC 'zsh --version | grep -q "zsh"'; then
            echo 'Zsh installed: pass' && exit 0
          else
            echo '::error ::Zsh installed: fail' && exit 1
          fi

      - name: Validate Ansible changes in host - nodejs & nvm & Yarn
        run: |
          if $DOCKER_COMPOSE_EXEC 'node --version | grep -Eq "^v[0-9.]+$"'; then
            echo 'Nodejs installed: pass' && exit 0
          else
            echo '::error ::Nodejs installed: fail' && exit 1
          fi

          if $DOCKER_COMPOSE_EXEC 'nvm --version | grep -Eq "^[0-9.]+$"'; then
            echo 'Nvm installed: pass' && exit 0
          else
            echo '::error ::Nvm installed: fail' && exit 1
          fi

          if $DOCKER_COMPOSE_EXEC 'yarn --version | grep -Eq "^[0-9.]+$"'; then
            echo 'Yarn installed: pass' && exit 0
          else
            echo '::error ::Yarn installed: fail' && exit 1
          fi

      - name: Validate Ansible changes in host - PHP & Composer
        run: |
          if $DOCKER_COMPOSE_EXEC 'php --version | grep -q "PHP"'; then
            echo 'PHP installed: pass' && exit 0
          else
            echo '::error ::PHP installed: fail' && exit 1
          fi

          if $DOCKER_COMPOSE_EXEC 'composer --version | grep -q "Composer"'; then
            echo 'Composer installed: pass' && exit 0
          else
            echo '::error ::Composer installed: fail' && exit 1
          fi

      - name: Test Ansible playbook idempotence issues
        run: $DOCKER_COMPOSE_EXEC "wget -qO- '""$INSTALL_SCRIPT""' | sh"
