---
name: Shared - Tests - Docker

"on":
  workflow_call:

permissions: {}

jobs:
  build-images:
    # yamllint disable-line rule:line-length
    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@f9e149b6cdfa8443994994f10085691a57b8cf0e # 0.27.1
    permissions:
      contents: read
      packages: write
      issues: read
      pull-requests: read
      # FIXME: This is a workaround for having workflow actions.
      # See https://github.com/orgs/community/discussions/38659
      id-token: write
    with:
      oci-registry: ${{ vars.OCI_REGISTRY }}
      images: |
        [
          {
            "name": "ubuntu-ci",
            "context": "./docker/ubuntu",
            "dockerfile": "Dockerfile",
            "platforms": ["linux/amd64"]
          },
          {
            "name": "test-ci",
            "context": "./docker/test",
            "dockerfile": "Dockerfile",
            "platforms": ["linux/amd64"]
          }
        ]
    secrets:
      oci-registry-password: ${{ secrets.GITHUB_TOKEN }}

  tests-docker:
    name: Tests - Docker
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    needs: build-images
    # jscpd:ignore-start
    env:
      BITWARDEN_CLIENT_ID: ${{ secrets.BITWARDEN_CLIENT_ID }}
      BITWARDEN_CLIENT_SECRET: ${{ secrets.BITWARDEN_CLIENT_SECRET }}
      BITWARDEN_PASSWORD: ${{ secrets.BITWARDEN_PASSWORD }}
      # yamllint disable-line rule:line-length
      INSTALL_SCRIPT: https://raw.githubusercontent.com/neilime/ubuntu-config/${{ github.head_ref || github.ref_name }}/install.sh
      REPOSITORY_URL: ${{ github.event.repository.clone_url }}
      REPOSITORY_BRANCH: ${{ github.head_ref || github.ref_name }}
      # yamllint disable-line rule:line-length
      UBUNTU_IMAGE: ${{ fromJSON(needs.build-images.outputs.built-images).ubuntu-ci.images[0] }}
      # yamllint disable-line rule:line-length
      TEST_IMAGE: ${{ fromJSON(needs.build-images.outputs.built-images).test-ci.images[0] }}
      # yamllint disable-line rule:line-length
      DOCKER_COMPOSE_EXEC: docker compose -f compose.ci.yml exec --user kasm-user -T ubuntu sh -c
    # jscpd:ignore-end
    steps:
      - name: Checkout code
        # yamllint disable-line rule:line-length
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # yamllint disable-line rule:line-length
      - uses: hoverkraft-tech/compose-action@40041ff1b97dbf152cd2361138c2b03fa29139df # v2.3.0
        with:
          compose-file: compose.ci.yml

      - name: Run install script
        run: $DOCKER_COMPOSE_EXEC "wget -qO- '""$INSTALL_SCRIPT""' | sh"

      - name: Run TestInfra tests using test service
        run: |
          docker compose -f compose.ci.yml run --rm test \
            python3 -m pytest tests/ --verbose

      - name: Test Ansible playbook idempotence
        # yamllint disable-line rule:line-length
        run: $DOCKER_COMPOSE_EXEC "wget -qO- '""$INSTALL_SCRIPT""' | sh"
