name: "Pull Request - Semantic Lint"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions: {}

jobs:
  main:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/semantic-pull-request.yml@b7dd413209df265bef8d7eb0efb117eaabc684c4 # 0.27.0
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
