name: Pull request - Continuous Integration

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/__shared-ci.yml
    permissions:
      actions: read
      contents: read
      statuses: write
      security-events: write
      packages: write
      issues: read
      pull-requests: read
      # FIXME: This is a workaround for having workflow actions. See https://github.com/orgs/community/discussions/38659
      id-token: write
    with:
      sign-images: false
    secrets: inherit
